<option value="CTL">CT ScHumS / CTL</option>
<option value="CTK">CT DOC ENCG / CTK</option>
<option value="CTG">CTGéstion / CTG</option>
<option value="NDD">CTN Doc FD / NDD</option>
<option value="NDL">CTN Doc Lt / NDL</option>
<option value="NDS">CTN Doc Sc / NDS</option>
<option value="TDE">CTN DocESE / TDE</option>
<option value="TDL">CTN DocLan / TDL</option>
<option value="NDR">CTN Droit / NDR</option>
<option value="NSE">CTN ESEFK / NSE</option>
<option value="NST">CTN EST K / NST</option>
<option value="NFC">CTN FC ENC / NFC</option>
<option value="NFS">CTN FC Sci / NFS</option>
<option value="TSP">CTN IMSpor / TSP</option>
<option value="CTH">CTN Lang / CTH</option>
<option value="TLA">CTN LicLan / TLA</option>
<option value="NMH">CTN M Lang / NMH</option>
<option value="NML">CTN M Lett / NML</option>
<option value="MDR">CTN MS Dro / MDR</option>
<option value="MTD">CTN Mas FD / MTD</option>
<option value="TMA">CTN MasLan / TMA</option>
<option value="CTN">CTN Univ / CTN</option>
<option value="CTC">CTN_ENCG / CTC</option>
<option value="CTA">CTN_ENSA / CTA</option>
<option value="CEC">CTN_ENSC / CEC</option>
<option value="CTS">CTSciences / CTS</option>
<option value="CTE">CT_NSA_DOC / CTE</option>
