<?php

return [

    'centres_gestion' => [
        'GLA' => 'Cent Gestion Lic fac Langue, litt,art / GLA',
        'FCC' => 'Centre Gestion FC ENCG / FCC',
        'MGA' => 'Centre Gestion Master F Lang Lettre Arts / MGA',
        'MGL' => 'Centre Gestion Master F Sc Hum Sociale / MGL',
        'CGC' => 'Centre Géstion ENCG / CGC',
        'CGA' => 'Centre de Gestion ENSA Kenitra / CGA',
        'GST' => 'Centre de Gestion EST Kenitra / GST',
        'ECG' => 'Centre de Gestion Ecole Nat Sup Chimie K / ECG',
        'CFC' => 'Centre de Gestion formation Continu F.Sc / CFC',
        'MGJ' => 'Centre de GestionMaster F Sc JuridiquesP / MGJ',
        'CGK' => 'Centre de Géstion Central de Kénitra / CGK',
        'CDD' => 'Centre de gestion CED Droit, Eco Gestion / CDD',
        'CDS' => 'Centre de gestion CED Science / CDS',
        'CGE' => 'Centre de gestion Ecole Sup Edu Form Ken / CGE',
        'CDN' => 'Centre de gestion doctorat ENCG / CDN',
        'CDF' => 'Centre de gestion doctorat ESEF / CDF',
        'CDA' => 'Centre de gestion doctorat LANG / CDA',
        'CGL' => 'Centre de géstion Fac. Sc Hum Sociales / CGL',
        'MGD' => 'Centre de géstion Mast F.Sc.Eco.Ges / MGD',
        'CGS' => 'Centre de géstion de la fac des Sciences / CGS',
        'CMS' => 'Centre de géstion des Métiers de Sport / CMS',
        'CGD' => 'Centre de géstion fac.Sc.Eco.Ges / CGD',
        'CGJ' => 'Centre gestion FacSc Juridique Politique / CGJ',
        'CDE' => 'Centre étude doctorale ENSA / CDE',
        'CDL' => 'Centre de gestion CED Lettres et sc.Huma / CDL',
    ],

    'centres_traitement' => [
        'CTL' => 'CT ScHumS / CTL',
        'CTK' => 'CT DOC ENCG / CTK',
        'CTG' => 'CTGéstion / CTG',
        'NDD' => 'CTN Doc FD / NDD',
        'NDL' => 'CTN Doc Lt / NDL',
        'NDS' => 'CTN Doc Sc / NDS',
        'TDE' => 'CTN DocESE / TDE',
        'TDL' => 'CTN DocLan / TDL',
        'NDR' => 'CTN Droit / NDR',
        'NSE' => 'CTN ESEFK / NSE',
        'NST' => 'CTN EST K / NST',
        'NFC' => 'CTN FC ENC / NFC',
        'NFS' => 'CTN FC Sci / NFS',
        'TSP' => 'CTN IMSpor / TSP',
        'CTH' => 'CTN Lang / CTH',
        'TLA' => 'CTN LicLan / TLA',
        'NMH' => 'CTN M Lang / NMH',
        'NML' => 'CTN M Lett / NML',
        'MDR' => 'CTN MS Dro / MDR',
        'MTD' => 'CTN Mas FD / MTD',
        'TMA' => 'CTN MasLan / TMA',
        'CTN' => 'CTN Univ / CTN',
        'CTC' => 'CTN_ENCG / CTC',
        'CTA' => 'CTN_ENSA / CTA',
        'CEC' => 'CTN_ENSC / CEC',
        'CTS' => 'CTSciences / CTS',
        'CTE' => 'CT_NSA_DOC / CTE',
    ],

    'centres_inscription_pedagogique' => [
        'MPD' => 'Centre Inscrip pédag Mast FSJES / MPD',
        'PMS' => 'Centre Inscrip pédagog Mét Sport / PMS',
        'PFC' => 'Centre Inscript pédag ForConti ENCG / PFC',
        'PFS' => 'Centre Inscript pédag ForConti Fac. Scien / PFS',
        'PLJ' => 'Centre Inscript pédag Lic Jurd / PLJ',
        'PLA' => 'Centre Inscript pédag Lic fac lang art / PLA',
        'PMA' => 'Centre Inscript pédag Mas LLA / PMA',
        'PML' => 'Centre Inscript pédag Mast F SHS / PML',
        'PMJ' => 'Centre Inscript pédag Mast Jurd / PMJ',
        'PDF' => 'Centre Inscription pédagogique Droit Fra / PDF',
        'CPC' => 'Centre Inscription pédagogique ENCG / CPC',
        'CPA' => 'Centre Inscription pédagogique ENSAK / CPA',
        'PET' => 'Centre Inscription pédagogique EST / PET',
        'CPL' => 'Centre Inscription pédagogique Fac. SHS / CPL',
        'CPD' => 'Centre Inscription pédagogique Fac.SJE / CPD',
        'CP' => 'Centre Inscription pédagogique Fac. Scien / CP',
        'CPK' => 'Centre Inscription pédagogique Kénitra / CPK',
        'PEC' => 'Centre inscrip pédag Ecole Nat Sup Chimi / PEC',
        'PEE' => 'Centre inscrip pédag Ecole Sup Edu Form / PEE',
    ],

    'centres_incompatibilite' => [
        'CIE_FLLA' => "Centre d'Incompatibilié FLLA / CIE_FLLA",
        'CIE_ENCG' => "Centre d'Incompatibilié d'Epreuves ENCG / CIE_ENCG",
        'CIE_ENSC' => "Centre d'Incompatibilié d'Epreuves ENSC / CIE_ENSC",
        'CIE_ESFE' => "Centre d'Incompatibilié d'Epreuves ESEF / CIE_ESFE",
        'CIE_ESTK' => "Centre d'Incompatibilié d'Epreuves ESTK / CIE_ESTK",
        'CIE_SCIENC' => "Centre d'Incompatibilié d'Epreuves Scien / CIE_SCIENC",
        'CIE_DROIT' => "Centre d'incompatibilité Fac Sciences Ju / CIE_DROIT",
        'CIE_ENSA' => "Centre d'incompatibilité d'Epreuves ENSA / CIE_ENSA",
        'CIE_ECONOM' => "Centre d'incompatibilité d'Epreuves Econ / CIE_ECONOM",
        'CIE_LETTRE' => "Centre d'incompatibilité d'Epreuves Lett / CIE_LETTRE",
    ],

];
